name: Lint & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libjack-jackd2-dev pkg-config

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Lint
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libjack-jackd2-dev pkg-config

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Test
        run: make test
